//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazlabdeneme.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yazlabdeneme.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap a99u6owju {
            get {
                object obj = ResourceManager.GetObject("a99u6owju", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap arkaplan {
            get {
                object obj = ResourceManager.GetObject("arkaplan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ayz85yun8 {
            get {
                object obj = ResourceManager.GetObject("ayz85yun8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ca85ff9d93475ec3aa8811013ea13e9d {
            get {
                object obj = ResourceManager.GetObject("ca85ff9d93475ec3aa8811013ea13e9d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ca85ff9d93475ec3aa8811013ea13e9d1 {
            get {
                object obj = ResourceManager.GetObject("ca85ff9d93475ec3aa8811013ea13e9d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] girisresmi {
            get {
                object obj = ResourceManager.GetObject("girisresmi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_alcohol_bottle_glass_pink_liquid_square_shape_liqu_alcohol_bottle_with_pink_liquid_and_glass656c1112610b55_8554896017015810743975 {
            get {
                object obj = ResourceManager.GetObject("transparent-alcohol-bottle-glass-pink-liquid-square-shape-liqu-alcohol-bottle-wit" +
                        "h-pink-liquid-and-glass656c1112610b55.8554896017015810743975", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_alcohol_bottle_glass_pink_liquid_square_shape_liqu_alcohol_bottle_with_pink_liquid_and_glass656c1112610b551 {
            get {
                object obj = ResourceManager.GetObject("transparent-alcohol-bottle-glass-pink-liquid-square-shape-liqu-alcohol-bottle-wit" +
                        "h-pink-liquid-and-glass656c1112610b551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_clear_glass_bottle_liquid_with_bubbles_pink_liquid_pink_frothy_liquid_in_clear_glass_bottle656b71b09a2c28_2298221417015402726315 {
            get {
                object obj = ResourceManager.GetObject("transparent-clear-glass-bottle-liquid-with-bubbles-pink-liquid-pink-frothy-liquid" +
                        "-in-clear-glass-bottle656b71b09a2c28.2298221417015402726315", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_salt_shaker_salt_shaker_glass_bottle_kitchen_seaso_plain_salt_bottle_with_black_lettering65e28bb06029e1_6165942617093457123939 {
            get {
                object obj = ResourceManager.GetObject("transparent-salt-shaker-salt-shaker-glass-bottle-kitchen-seaso-plain-salt-bottle-" +
                        "with-black-lettering65e28bb06029e1.6165942617093457123939", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
